
pm uninstall -k --user 0 com.netflix.mediaclient
pm uninstall -k --user 0 com.samsung.android.mobileservice
pm uninstall -k --user 0 com.osp.app.signin
pm uninstall -k --user 0 com.samsung.android.scloud
pm uninstall -k --user 0 com.google.android.projection.gearhead
pm uninstall -k --user 0 com.samsung.android.bixby.agent
pm uninstall -k --user 0 com.samsung.android.app.settings.bixby
pm uninstall -k --user 0 com.microsoft.appmanager
pm uninstall -k --user 0 com.samsung.android.app.tips
pm uninstall -k --user 0 com.sec.android.daemonapp
pm uninstall -k --user 0 com.samsung.android.themestore
pm uninstall -k --user 0 com.android.printspooler
pm uninstall -k --user 0 com.android.bprint
pm uninstall -k --user 0 com.facebook.services
pm uninstall -k --user 0 com.facebook.system
pm uninstall -k --user 0 com.samsung.android.bixbyvision.framework
pm uninstall -k --user 0 com.samsung.android.smartmirroring
pm uninstall -k --user 0 com.sec.android.app.magnifier
pm uninstall -k --user 0 com.google.android.apps.restore
pm uninstall -k --user 0 com.samsung.android.aware.service
pm uninstall -k --user 0 com.samsung.android.app.omcagent
pm uninstall -k --user 0 com.samsung.android.mapsagent
pm uninstall -k --user 0 com.sec.android.app.quicktool
pm uninstall -k --user 0 com.sec.android.app.billing
pm uninstall -k --user 0 com.samsung.android.stickercenter
pm uninstall -k --user 0 com.samsung.app.newtrim
pm uninstall -k --user 0 com.samsung.android.visualars
pm uninstall -k --user 0 com.google.android.apps.docs.editors.sheets
pm uninstall -k --user 0 com.google.mainline.adservices
pm uninstall -k --user 0 com.google.android.adservices.api
pm uninstall -k --user 0 com.android.bookmarkprovider
pm uninstall -k --user 0 com.android.dreams.basic
pm uninstall -k --user 0 com.android.dreams.phototable
pm uninstall -k --user 0 com.android.egg
pm uninstall -k --user 0 com.android.hotwordenrollment.okgoogle
pm uninstall -k --user 0 com.android.hotwordenrollment.xgoogle
pm uninstall -k --user 0 com.google.android.providers.partnerbookmarks
pm uninstall -k --user 0 com.sec.android.app.samsungapps
pm uninstall -k --user 0 com.samsung.android.dynamiclock
pm uninstall -k --user 0 com.samsung.android.tvplus
pm uninstall -k --user 0 com.samsung.android.app.watchmanagerstub
pm uninstall -k --user 0 com.samsung.android.app.watchmanager
pm uninstall -k --user 0 com.samsung.android.waterplugin
pm uninstall -k --user 0 com.samsung.android.accessibility.talkback
pm uninstall -k --user 0 com.samsung.android.bixby.wakeup
pm uninstall -k --user 0 com.sec.android.app.shealth
pm uninstall -k --user 0 com.samsung.android.arzone
pm uninstall -k --user 0 com.google.android.apps.docs
pm uninstall -k --user 0 com.google.android.apps.tachyon
pm uninstall -k --user 0 com.google.android.feedback
pm uninstall -k --user 0 com.google.android.googlequicksearchbox
pm uninstall -k --user 0 com.google.android.marvin.talkback
pm uninstall -k --user 0 com.google.android.printservice.recommendation
pm uninstall -k --user 0 com.google.android.syncadapters.calendar
pm uninstall -k --user 0 com.google.android.tts
pm uninstall -k --user 0 com.google.android.apps.youtube.music
pm uninstall -k --user 0 com.google.ar.core
pm uninstall -k --user 0 com.sec.android.mimage.avatarstickers
pm uninstall -k --user 0 com.samsung.android.aremojieditor
pm uninstall -k --user 0 com.android.bips
pm uninstall -k --user 0 com.samsung.android.game.gametools
pm uninstall -k --user 0 com.samsung.android.game.gos
pm uninstall -k --user 0 com.samsung.android.kidsinstaller
pm uninstall -k --user 0 com.samsung.android.app.camera.sticker.facearavatar.preload
pm uninstall -k --user 0 com.sec.android.app.sbrowser
pm uninstall -k --user 0 com.sec.android.easyMover.Agent
pm uninstall -k --user 0 com.samsung.android.calendar
pm uninstall -k --user 0 com.sec.android.dexsystemui
pm uninstall -k --user 0 com.sec.android.app.desktoplauncher
pm uninstall -k --user 0 com.synchronoss.dcs.att.r2g
pm uninstall -k --user 0 com.wavemarket.waplauncher
pm uninstall -k --user 0 com.pandora.android
pm uninstall -k --user 0 com.sec.penup
pm uninstall -k --user 0 com.wb.goog.got.conquest
pm uninstall -k --user 0 com.foxnextgames.m3
pm uninstall -k --user 0 com.microsoft.skydrive
pm uninstall -k --user 0 com.claromusica
pm uninstall -k --user 0 com.clarovideo
pm uninstall -k --user 0 com.clarocloud
pm uninstall -k --user 0 com.claroshop
pm uninstall -k --user 0 com.claropay
pm uninstall -k --user 0 com.claro.tv
pm uninstall -k --user 0 com.claro.empresas
pm uninstall -k --user 0 com.claro.assistant
pm uninstall -k --user 0 com.claro.photoeditor
pm uninstall -k --user 0 com.samsung.android.fmm
pm uninstall -k --user 0 com.sec.android.app.ve.vebgm
pm uninstall -k --user 0 com.claro.store
pm uninstall -k --user 0 com.samsung.android.bixby.esdk.globalconstant
pm uninstall -k --user 0 com.samsung.android.bluelightfilter
pm uninstall -k --user 0 com.samsung.android.app.sharelive
pm uninstall -k --user 0 com.sec.android.app.fm
pm uninstall -k --user 0 com.samsung.android.themecenter
ilter
pm uninstall -k --user 0 com.samsung.android.app.sharelive
pm uninstall -k --user 0 com.sec.android.app.fm
pm uninstall -k --user 0 com.samsung.android.themecenter
